apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: tenancy.kcp.dev
spec:
  latestResourceSchemas:
  - v221212-cf67ac73a.clusterworkspaces.tenancy.kcp.dev
  - v221212-cf67ac73a.clusterworkspacetypes.tenancy.kcp.dev
  - v221212-cf67ac73a.workspaces.tenancy.kcp.dev
  maximalPermissionPolicy:
    local: {}
status: {}
