apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: tenancy.kcp.dev
spec:
  latestResourceSchemas:
  - v221204-5bf97087f.workspaces.tenancy.kcp.dev
  - v221206-46974e3a0.clusterworkspacetypes.tenancy.kcp.dev
  - v221207-4f1bcfa1d.clusterworkspaces.tenancy.kcp.dev
  maximalPermissionPolicy:
    local: {}
status: {}
