apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: tenancy.kcp.dev
spec:
  latestResourceSchemas:
  - v220923-596b9074.clusterworkspacetypes.tenancy.kcp.dev
  - v221006-eaaf199d.clusterworkspaces.tenancy.kcp.dev
  - v221110-a0af4384.workspaces.tenancy.kcp.dev
  maximalPermissionPolicy:
    local: {}
status: {}
