apiVersion: apis.kcp.dev/v1alpha1
kind: APIResourceSchema
metadata:
  creationTimestamp: null
  name: v221109-0bad79f0.thisworkspaces.tenancy.kcp.dev
spec:
  group: tenancy.kcp.dev
  names:
    categories:
    - kcp
    kind: ThisWorkspace
    listKind: ThisWorkspaceList
    plural: thisworkspaces
    singular: thisworkspace
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: The current phase (e.g. Scheduling, Initializing, Ready)
      jsonPath: .status.phase
      name: Phase
      type: string
    - description: Type of the workspace
      jsonPath: .spec.type.name
      name: Type
      type: string
    - description: URL to access the workspace
      jsonPath: .status.URL
      name: URL
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      description: ThisWorkspace describes the current workspace.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          properties:
            name:
              enum:
              - this
              type: string
          type: object
        spec:
          default: {}
          type: object
        status:
          description: ThisWorkspaceStatus communicates the observed state of the
            Workspace.
          properties:
            conditions:
              description: Current processing state of the ThisWorkspace.
              items:
                description: Condition defines an observation of a object operational
                  state.
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another. This should be when the underlying condition changed.
                      If that is not known, then using the time when the API field
                      changed is acceptable.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition. This field may be empty.
                    type: string
                  reason:
                    description: The reason for the condition's last transition in
                      CamelCase. The specific API may choose whether or not this field
                      is considered a guaranteed API. This field may not be empty.
                    type: string
                  severity:
                    description: Severity provides an explicit classification of Reason
                      code, so the users or machines can immediately understand the
                      current situation and act accordingly. The Severity field MUST
                      be set only when Status=False.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                      Many .condition.type values are consistent across resources
                      like Available, but because arbitrary conditions can be useful
                      (see .node.status.conditions), the ability to deconflict is
                      important.
                    type: string
                required:
                - lastTransitionTime
                - status
                - type
                type: object
              type: array
            initializers:
              description: initializers are set on creation by the system and must
                be cleared by a controller before the workspace can be used. The ThisWorkspace
                will stay in the phase "Initializing" state until all initializers
                are cleared.
              items:
                description: ClusterWorkspaceInitializer is a unique string corresponding
                  to a cluster workspace initialization controller for the given type
                  of workspaces.
                pattern: ^(root(:[a-z0-9]([-a-z0-9]*[a-z0-9])?)*(:[a-z][a-z0-9]([-a-z0-9]*[a-z0-9])?))|(system:.+)$
                type: string
              type: array
            phase:
              description: Phase of the workspace (Initializing / Active / Terminating).
                This field is ALPHA.
              type: string
          type: object
      type: object
    served: true
    storage: true
    subresources:
      status: {}
